name: MochiLinkConnectorPMMP
version: 1.6.2
main: com\mochilink\connector\pmmp\MochiLinkPMMPPlugin
api: [5.0.0]
authors: [chm413]
description: Minecraft Bedrock Edition PMMP connector plugin for Mochi-Link unified management system
website: https://github.com/chm413/Mochi-Link

permissions:
  mochilink.admin:
    description: Full access to MochiLink commands
    default: op
  mochilink.manage:
    description: Manage server connections and settings
    default: op
  mochilink.monitor:
    description: View server status and monitoring data
    default: op

commands:
  mochilink:
    description: Main MochiLink command for PMMP
    usage: /mochilink <subcommand>
    permission: mochilink.admin
    aliases: [ml, mochi, mlp]
  
  mlstatus:
    description: Check MochiLink PMMP connection status
    usage: /mlstatus
    permission: mochilink.monitor
    
  mlreconnect:
    description: Reconnect to MochiLink management server
    usage: /mlreconnect
    permission: mochilink.manage